[project]
name = "be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard,uvicorn]>=0.115.12",
    "pydantic>=2.11.3",
    "typing>=3.10.0.0",
    "uvicorn>=0.34.2",
]
